import { StyleSheet } from 'react-native';
import { theme } from '../design/types';
export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: theme.background },
  grow: { flex: 1 },
  field: {
    position: 'absolute',
    padding: 0,
    margin: 0,
    color: theme.ink,
    fontFamily: 'Montserrat-Medium',
    includeFontPadding: false,
  },
  small: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 12,
    color: theme.muted,
    lineHeight: 20,
  },
  link: { fontFamily: 'Montserrat-Medium', fontSize: 17, color: theme.teal },
  empty: { padding: 25, backgroundColor: 'white', borderRadius: 25 },
  emptyTitle: {
    fontSize: 22,
    color: theme.navy,
    fontWeight: '700',
    marginBottom: 12,
  },
  courseTitle: { color: theme.ink, fontWeight: '700' },
  price: {
    position: 'absolute',
    backgroundColor: 'white',
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
  },
  priceText: { color: theme.ink, fontWeight: '700' },
  save: {
    position: 'absolute',
    backgroundColor: 'white',
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toast: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 120,
    padding: 14,
    backgroundColor: theme.navy,
    borderRadius: 18,
  },
  toastText: {
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
  },
  storageError: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    color: theme.danger,
    fontSize: 11,
    textAlign: 'center',
  },
  galleryTarget: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 24,
    height: 24,
  },
  authFooter: {
    color: '#707070',
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
    includeFontPadding: false,
  },
  authFooterLink: { fontWeight: '700' },
});
