// Original, silent 18-second UI/UX sample. This is not a supplied course video.
process.chdir(require('node:path').resolve(__dirname, '..'));
const fs=require('node:fs');const {spawnSync}=require('node:child_process');
const sharp=require('./tools/node_modules/sharp');const ffmpeg=require('./tools/node_modules/ffmpeg-static');
fs.mkdirSync('src/assets/media',{recursive:true});fs.mkdirSync('design/video',{recursive:true});
const slides=[['01 / UI & UX BASICS','Start with the learner','Understand a person’s goal before designing a screen.'],['02 / VISUAL HIERARCHY','Make the next step clear','Use spacing, contrast and one clear primary action.'],['03 / TEST & IMPROVE','Learn from real people','Test the flow. Listen, simplify, and iterate.']];
(async()=>{for(let i=0;i<slides.length;i++){const [k,t,b]=slides[i];const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#0b3954"/><circle cx="1180" cy="640" r="340" fill="#087e8b"/><rect x="80" y="80" width="120" height="8" rx="4" fill="#ffad33"/><text x="80" y="150" fill="#68dad6" font-family="Arial" font-size="26">SALFORD / LOCAL DEMO LESSON</text><text x="80" y="280" fill="#aecdd1" font-family="Arial" font-size="24">${k.replaceAll('&','&amp;')}</text><text x="80" y="375" fill="white" font-family="Arial" font-size="66" font-weight="bold">${t}</text><text x="80" y="450" fill="white" font-family="Arial" font-size="28">${b}</text><text x="80" y="640" fill="#aecdd1" font-family="Arial" font-size="21">Sample content · Replace with your licensed course videos</text></svg>`;await sharp(Buffer.from(svg)).png().toFile(`design/video/slide${i}.png`);}
fs.writeFileSync('design/video/list.txt',slides.map((_,i)=>`file 'slide${i}.png'\nduration 6`).join('\n')+"\nfile 'slide2.png'\n");
const r=spawnSync(ffmpeg,['-y','-f','concat','-safe','0','-i','design/video/list.txt','-vf','fps=24,format=yuv420p','-c:v','libx264','-preset','fast','-crf','24','-movflags','+faststart','-t','18','src/assets/media/ui-ux-preview.mp4'],{encoding:'utf8'});if(r.status)throw Error(r.stderr);console.log('Bundled local demo lesson ready.');})();
